[package]
name = "omo"
version = "0.1.0"
authors = ["guyfedwards <guyfedwards@gmail.com>"]
edition = "2018"

[[bin]]
name = "omo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
notify-rust = "4.5.2"
